version: '3.8'

services:
  webserver:
    build: .
    ports:
      - 8090:80
    networks:
      - connwebserver
    volumes:
      - dev:/var/www/
  serverdb:
    image: mariadb:latest
    environment:
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: 1
    ports:
      - 3306:3306
    networks:
      - connwebserver
      - connserverdb
    volumes:
      - mysqldata:/mysqldata/
      
  servercache:
    image: redis:latest
    ports:
      - 6379:6379
    networks:
      - connserverdb
    volumes:
      - redisdata:/redis/data
  clientedb:
    image: phpmyadmin:latest
    environment:
      - PMA_USER=root
    ports:
      - 8080:80
    networks:
      - connserverdb

volumes:
  mysqldata:
  dev:
  redisdata:
  
networks:
  connwebserver:
    driver: bridge
  connserverdb:
    driver: bridge

  